const ScreenNames = {
  HOME: 'Home',
  TRIP: 'Trip',
  TRIPDETAILS: 'TripDetails',
  LOGIN: 'Login',
  SIGNUP: 'SignUp',
  FORGOTPASSWORD: 'ForgotPassword',
  PROFILE: 'Profile',
  EDITPROFILE: 'EditProfile',
  OFFERS: 'Offers',
  OFFERDETAILS: 'OfferDetails',
  HOMEBASE: 'HomeBase',
  NOTIFICATION: 'Notification',
  PAYMENT: 'Payment',
  TRANSACTION: 'Transaction',
  TRANSACTIONDETAILS: 'TransactionDetails',
  TOPDESTINATIONDETAILS: 'TopDestinationDetails',
  FULLFEATURELIST: 'FullFeatureList',
  SETTING: 'Setting',
  SEARCH: 'Search',
  REVIEWS: 'Reviews',
  SENDOFFER: 'SendOffer',
  LEAVERATING: 'LeaveRating',
};

export default ScreenNames;
